use tsvm_bytecode::{
    compile_source, decode_module, encode_module, verify_module, BytecodeModule, Instruction,
    Opcode, TypeTag, VerifyErrorCode,
};

fn initial_demo_source() -> &'static str {
    r#"
interface Account {
  id: number;
  balance: number;
}

function credit(account: Account, amount: number): number {
  account.balance += amount;
  return account.balance;
}

const account: Account = {
  id: 1,
  balance: 100
};

console.log(credit(account, 50));
"#
}

#[test]
fn compiles_initial_demo_to_verified_bytecode() {
    let output = compile_source(initial_demo_source());

    assert!(output.diagnostics.is_empty(), "{:?}", output.diagnostics);
    let module = output.module.expect("valid source should compile");
    verify_module(&module).expect("generated bytecode should verify");

    assert_eq!(module.header.magic, *b"TSVM");
    assert_eq!(module.header.version, 1);
    assert!(module
        .functions
        .iter()
        .any(|function| function.name == "credit"));
    assert!(module
        .functions
        .iter()
        .any(|function| function.name == "__entry"));
    assert!(!module.constants.is_empty());
    assert!(!module.source_map.is_empty());
}

#[test]
fn bytecode_encoding_is_deterministic_and_decodes_safely() {
    let module = compile_source(initial_demo_source())
        .module
        .expect("valid source should compile");

    let first = encode_module(&module);
    let second = encode_module(&module);
    assert_eq!(first, second);

    let decoded = decode_module(&first).expect("encoded bytecode should decode");
    assert_eq!(decoded, module);
    verify_module(&decoded).expect("decoded bytecode should verify");
}

#[test]
fn decoder_rejects_malformed_header() {
    let err = decode_module(b"NOPE").expect_err("bad magic should not decode");
    assert!(err.message.contains("magic"));
}

#[test]
fn verifier_rejects_invalid_constant_reference() {
    let mut module = valid_module();
    module.functions[0].blocks[0].instructions[0].operands[0] = 999;

    let errors = verify_module(&module).expect_err("invalid constant reference should fail");
    assert!(errors
        .iter()
        .any(|error| error.code == VerifyErrorCode::InvalidConstantReference));
}

#[test]
fn verifier_rejects_invalid_value_reference() {
    let mut module = valid_module();
    module.functions[0].blocks[0]
        .instructions
        .push(Instruction {
            opcode: Opcode::StoreLocal,
            operands: vec![0, 999],
            type_tag: TypeTag::Number,
            source_ref: 0,
        });

    let errors = verify_module(&module).expect_err("invalid value reference should fail");
    assert!(errors
        .iter()
        .any(|error| error.code == VerifyErrorCode::InvalidValueReference));
}

#[test]
fn verifier_rejects_invalid_jump_target() {
    let mut module = valid_module();
    module.functions[0].blocks[0]
        .instructions
        .push(Instruction {
            opcode: Opcode::Jump,
            operands: vec![42],
            type_tag: TypeTag::Undefined,
            source_ref: 0,
        });

    let errors = verify_module(&module).expect_err("invalid jump target should fail");
    assert!(errors
        .iter()
        .any(|error| error.code == VerifyErrorCode::InvalidJumpTarget));
}

#[test]
fn compiles_valid_bytecode_fixture_corpus() {
    let fixture_root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("tests")
        .join("fixtures")
        .join("bytecode")
        .join("valid");

    for entry in std::fs::read_dir(&fixture_root).expect("bytecode fixture directory should exist")
    {
        let path = entry.expect("fixture entry should be readable").path();
        if !path.is_file() {
            continue;
        }

        let source = std::fs::read_to_string(&path).expect("fixture should be readable");
        let output = compile_source(&source);
        assert!(
            output.diagnostics.is_empty(),
            "{} diagnostics: {:?}",
            path.display(),
            output.diagnostics
        );
        let module = output.module.expect("fixture should compile to bytecode");
        verify_module(&module).expect("fixture bytecode should verify");
        let decoded = decode_module(&encode_module(&module)).expect("fixture should roundtrip");
        assert_eq!(decoded, module);
    }
}

fn valid_module() -> BytecodeModule {
    compile_source("const answer: number = 42;")
        .module
        .expect("valid source should compile")
}
